### ISSUE TITLE
No "ding" in Mobile Safari

### ISSUE THREAD

**Issue by alexlafroscia** [tholman/elevator.js#1]
Hey, I know this is mostly a gag so you might not care, but you don't get the "ding" in Mobile Safari.  My guess is that it's the fact that iOS requires user intervention to play audio on websites?  I'm not sure if there's a way around it.

**Comment by mralext20** [comment]
Not just iOS, also android. I think its part of the browser spec. 

Eitherway, a good way to solve this issue is to not play noise on mobile.

**Comment by romainst** [comment]
You could possibly do a playlist with the 2 files and skip to the second one after a timeout?

**Comment by dabockster** [comment]
Maybe some sort of flash (like a camera flash) should be implemented. A visual option instead of a sound. Also works for people with hearing issues.

**Comment by omarreiss** [comment]
Guys, that's totally unacceptable. No ding, no elevator...

**Comment by tholman** [comment]
Just going to let this slide, anyhow. Its a gag ;)
