### ISSUE TITLE
Setting volume

### ISSUE THREAD

**Issue by mewcrazy** [tholman/elevator.js#113]
Hey is there any way to set the volume of the mp3?

I tried reducing it's volume, but it doesn't seem to work in my Opera. 

Kind Regards,
Dennis Bitsch

**Comment by donroyco** [comment]
You _could_ use the Web APIs volume property: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

**Comment by mewcrazy** [comment]
Thanks, I've seen that. But I didn't know how to implement it. Could you tell me at which line I'd need to add it to make it work?

**Comment by tholman** [comment]
Hi!

To set the audio volume, you'd probably want to set it after this line - https://github.com/tholman/elevator.js/blob/master/elevator.js#L243

`mainAudio.volume = 0.5`

You may want to do the same for the endAudio element too :)

Let me know how it goes, and if you're still having trouble I can help you out.

**Comment by amr-fawzy** [comment]
sorry im not good in english ,, what u want You can simplify it؟

2017-05-07 12:48 GMT+02:00 Dennis Bitsch <notifications@github.com>:

**Comment by tholman** [comment]
Going to close this for now, volume isn't something I want to incorporate into the lib, but the instructions are there for anyone who would like to modify it that way.
