### ISSUE TITLE
No Git tags in GitHub repo

### ISSUE THREAD

**Issue by dakshshah96** [tholman/elevator.js#114]
Hey @tholman,

I'd like to host your library, elevator.js on cdnjs — It is one of the most famous free and public web front-end CDN services which is used by ~1,143,000 websites worldwide.

The git auto-updater for cdnjs relies on git tags to recognize a release version and automatically update the library in the cdnjs repo.

If it's not too much to ask, can you please add git tags for this repo, say 1.0.0?

**Note**: Even though this package is available on npm and I'll be using npm for the auto-update code, I'm suggesting the addition of release tags as a fail safe method.

**Comment by tholman** [comment]
Done!
