### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by xypaul** [tholman/elevator.js#12]
Cool, but I find the demo on the homepage awkwardly slow.

**Comment by seanjohnson08** [comment]
Ever taken a real elevator? It isn't instant!

**Comment by PanArnaud** [comment]
It was my first impression too. But then I really feel like in an elevator ! Gj

**Comment by ummahusla** [comment]
Kinda can agree with you. But anyway you can change the speed.

**Comment by Trii** [comment]
@xypaul it isn't quite as awkward if you take the time to enjoy the music.

**Comment by tholman** [comment]
Haha, awkward is definitely the point. But you can change the speed if you want to use it functionally :dancer:
