### ISSUE TITLE
Volume settings

### ISSUE THREAD

**Issue by aZolo77** [tholman/elevator.js#123]
Can you add an opportunity to tune the volume cause if a user has high volume settings it can really bother.. Thanks

**Comment by aZolo77** [comment]
I did it here:

if (_options.mainAudio) {
            mainAudio = new Audio(_options.mainAudio);
            mainAudio.volume = 0.3;  //========> HERE
            mainAudio.setAttribute("preload", _options.preloadAudio);
            mainAudio.setAttribute("loop", _options.loopAudio);
        }

and it works.
but i dont know how to add it in opts..

**Comment by tholman** [comment]
Leaving this out to keep it simple. If you want the audio to be lower, you should make the audio volume of the file softer.
