### ISSUE TITLE
Doesn't allow multiple variations of elevator options on a single page

### ISSUE THREAD

**Issue by seanjohnson08** [tholman/elevator.js#13]
I'd fix this if I weren't on mobile, but basically - because the configuration options are not instance variables, whatever "Elevator" that is created last overrides the configuration options for all previous Elevators. For example, by doing the following:

            var elevator1 = new Elevator({
                element: $('#button-one'),
                mainAudio: './music/elevator-music-one.mp3', // Music from http://www.bensound.com/
                endAudio:  './music/ding-one.mp3',
                duration: 1000
            });

            var elevator2 = new Elevator({
                element: $('#button-two'),
                mainAudio: './music/elevator-music-two.mp3', // Music from http://www.bensound.com/
                endAudio:  './music/ding-two.mp3',
                duration: 5000
            });

`elevator` will have the configuration of `elevator2` even though I really wanted two different behaviors.

Thanks for making this, I had a good laugh. :)

**Comment by tholman** [comment]
Ahh nuts. Definitely an issue! Will sort that out when I grab a minute.

**Comment by tholman** [comment]
Should be fixed with #91 :dancer:
