### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [tholman/elevator.js#131]
Hello! I love this project! It's amazing to see what developers do with *their* spare time, isn't it...?

Anyway, I would just ask why the demonstration website uses Google Analytics. Also, the tracking code is not present in the source tree in this repository.

Would you be willing to remove this Google Analytics 'functionality' from this website? There are better alternatives if you _must_ keep tabs on users' activity.

Some reputable alternatives can be seen here: https://switching.software/replace/google-analytics/

**Comment by tholman** [comment]
That's the tracking on my personal website that houses the demo.
