### ISSUE TITLE
Example page is not long enough

### ISSUE THREAD

**Issue by hagbarddenstore** [tholman/elevator.js#14]
As the title say, I'd like the example page to be even longer! There isn't enough time to fully embrace the awesomeness which is elevator.js.

**Comment by sebie** [comment]
What I thought. Can I sumbit a PR @tholman or will you change it?

**Comment by lustremedia** [comment]
+1

**Comment by tholman** [comment]
Haha, I was thinking of configuring the scroll speed to be slower. But its all about getting people to scroll down enough... too much would drive people away. 

Haha, loving your enthusiasm for the sweet sweet elevator music though!

**Comment by sebie** [comment]
@tholman What if you created a `./long/index.html` file and just have a longer scroll there?
