### ISSUE TITLE
Music license?

### ISSUE THREAD

**Issue by emilv** [tholman/elevator.js#16]
Is the music licensed as MIT too? Given that it is included in this repo I assume it is, but it would help if that was clarified.

**Comment by sebie** [comment]
Well in the demo, if you `Inspect Element` you can find the following.

```
                mainAudio: './music/elevator-music.mp3', * // Music from http://www.bensound.com/ *
                endAudio:  './music/ding.mp3', * // Music from http://www.bensound.com/ *
```

I can't reach the website, but I found the [creators Twitter](https://twitter.com/bensound) and in the bio is the following: > Creative commons music.

That would be the licence, in my opinion?!

**Comment by tholman** [comment]
Right. The music is creative commons. Hence the links in the demo code. 

They're of-course for demo purposes only, the library expects you to use your own.

Thats a good point though, I'll include that in the readme.

**Comment by tholman** [comment]
Bam: https://github.com/tholman/elevator.js/commit/c19284d61c1b6c554fed22691694b6b86bc393f5

**Comment by Croydon** [comment]
Creative Commons is an organisation, not a specific license. The note that the music is Creative Commons is as helpful as no note at all. You could contact him on Twitter and ask for the specific license + license version.

**Comment by tholman** [comment]
You must have missed it, but the readme has a link to his site, which has the license - http://www.bensound.com/licensing , as does the code in the demo. 

Again, this is just the demo, it doesn't come packaged with the js, the intention is that you can use whichever music you like.

**Comment by Croydon** [comment]
Alright, this should still be avoided. Other people will read it and they will take it over, when they don't know it better. I read a few times too often "licensed under Creative Commons" ;)
