### ISSUE TITLE
bower and npm?

### ISSUE THREAD

**Issue by stevemao** [tholman/elevator.js#17]

**Comment by ahmedashraff** [comment]
What's the description of this issue ?

**Comment by dabockster** [comment]
Bower maybe, since this is a client side plugin.

**Comment by stevemao** [comment]
bower is the client side package manager. npm is the javascript package manager

**Comment by gh0stonio** [comment]
Hi, i made a PR for bower integration (https://github.com/tholman/elevator.js/pull/66).
It also contain an UMD implementation and Gulp to build the min file.

**Comment by gh0stonio** [comment]
Following discussions i closed previous PR and create this new one #67 (only include bower and umd)

**Comment by bercik809** [comment]
I think that npm.

**Comment by gh0stonio** [comment]
I wanted to add a build process with gulp, already write it and i will make another PR with it.
And in ordre to use gulp i made a package.json file so after this PR and the one i'll make the package will have a bower and npm structure. 
Only need to push it to npmjs after and done.
What do you think about this?

**Comment by xiangming** [comment]
Yup, we need bower or npm

**Comment by joni2back** [comment]
@xiangming @gh0stonio @bercik809  @stevemao @dabockster  @ahmedashraff 
Hi, can someone help me to support bower/npm in my project? [@angular-filemanager](https://github.com/joni2back/angular-filemanager)
Thanks in advance!

**Comment by stevemao** [comment]
@joni2back use `bower init` and `npm init` to generate these metadata

**Comment by tholman** [comment]
Appreciate the love, but not really looking to add it into any package managers. Happy as a stand alone joke, at the moment :dancer:
