### ISSUE TITLE
Tabbing away breaks

### ISSUE THREAD

**Issue by saml** [tholman/elevator.js#2]
1. Go http://tholman.com/elevator.js/
1. Scroll down. 
1. Click Back to Top. Music plays.
1. Open new tab and go to your favorite site that's SFW.
1. Music still plays on the other tab.
1. Yea feels so good~
1. Come back to elevator page.
1. Ding!
1. But still at the bottom.

**Comment by christianbundy** [comment]
I came here to create an issue specifically for this.

:+1:

**Comment by xplustwo** [comment]
Seconded

**Comment by sergiotapia** [comment]
It's a feature! 

\*keeps playing music*\

**Comment by xplustwo** [comment]
^

**Comment by tholman** [comment]
Fixed!

**Comment by xplustwo** [comment]
But now the music stops completely. What if i like hearing the music while im tabbed away and want to know when I return to the top?

**Comment by christianbundy** [comment]
[![workflow](https://cloud.githubusercontent.com/assets/537700/7281460/a65e429c-e8de-11e4-8d79-e17e1df234da.png)](https://xkcd.com/1172/)

**Comment by tholman** [comment]
Haha, can't win em all. This'll just be how it is :D
