### ISSUE TITLE
Strange behavior when coupled with the Home button

### ISSUE THREAD

**Issue by shotgunninja** [tholman/elevator.js#3]
Hey Tim,

I've been looking into using your library on a site that I'm setting up, and in doing research on the problem, I came across several suggestions of using the Home button on the keyboard in conjunction with this library. After setting up a test page, I tried using the Home button, and it bypassed the normal behavior and simply moved to the top of the page immediately. Do you have any suggestions as to how I could suppress this behavior? Perhaps some options in the library to intercept the Home button and use it to trigger the elevator behavior? I feel that this library would give my site the responsiveness and interactivity that it needs to really stand out.

Thanks in advance,

- Shotgun Ninja

**Comment by tholman** [comment]
Hey mate.

This isn't something elevator.js should really handle. You would do it by hijacking that keyboard event (preventing default and propagation), then calling `elevator.elevate();` 

Its never great to overload the browsers default functionality, but would definitely play into the joke ;)
