### ISSUE TITLE
Progressive enhancement

### ISSUE THREAD

**Issue by JanKlopper** [tholman/elevator.js#60]
Why not use the 'old fashioned way' of providing a link with a #top anchor?
That way, this at least degrades nicely for those not inclined to use JS.
As #top is a specialcase anchor, you wont need to name/id the body to make this work.

**Comment by YMIndustries** [comment]
In order to properly do this it is necessary to use the History API to push the new hash fragment into the URL without instantly scrolling the page. It's not too hard, but care should be taken to not degrade the elevation experience in older browsers.

**Comment by tholman** [comment]
Old fashioned way is referring to the music, which soothes the awkward silence. Feel free to use `#top` wherever you like :dancer:
