### ISSUE TITLE
Don't elevators go down, too?

### ISSUE THREAD

**Issue by jonleecraw** [tholman/elevator.js#62]
I understand the principal point behind a scroll-to-top mini-library... but it seems (on the thought level) that it would be trivial to implement scroll-to-bottom functionality! I prefer the stairs, but If I use an elevator, I probably use it both ways.

**Comment by tholman** [comment]
Haha, this elevator is modeled on the glass elevator from charlie and the chocolate factory. That goes up up up, and out of the building. Never to return.
