### ISSUE TITLE
Music is too loud

### ISSUE THREAD

**Issue by ca1ek** [tholman/elevator.js#63]
Really.

**Comment by tholman** [comment]
Feel free to you whatever music you like. This was the demo music I chose :dancer:

**Comment by ca1ek** [comment]
I like the music.

But I **do not** like my floor shaking and having police at my doorstep for being too loud past 10 PM.

**Comment by tholman** [comment]
Headphones are the way to go after 10pm. Although it won't save your eardrums. This library is made as a joke/easter egg, please don't take it to heart.
