### ISSUE TITLE
Problem when browser lost focus

### ISSUE THREAD

**Issue by mamadoo** [tholman/elevator.js#73]
Hello
When click back to top and then lost focus from browser, elevator goes to first of page and music stopped. Can anybody fix that?

**Comment by tholman** [comment]
We can't have it both ways. If you change tabs, I'm happy with the music stopping, and completing the "scroll to top" functionality.

Can't really convince myself that anything else would be worth the effort :)

**Comment by mamadoo** [comment]
Yes. You're right
