### ISSUE TITLE
.back-to-top class is hidden by the ad-blocker

### ISSUE THREAD

**Issue by Baldrs** [tholman/elevator.js#75]
I've noticed that the nice "go to top" button has been hidden by the adblocker because of 'back-to-top' class it has. Can this class name be changed to something more ad-blocker friendly?

**Comment by tholman** [comment]
Strange, why would an ad-blocker target the "back-to-top" class.

But yeah, should change it to "elevator" or something. Its an odd one though.

**Comment by KenPowers** [comment]
Which ad blocker on which platform / browser, by chance? I'm using [uBlock](https://chrismatic.io/ublock/) and didn't see anything out of the ordinary.

**Comment by tholman** [comment]
Updates now!

**Comment by Baldrs** [comment]
@KenPowers I use uBlock with privacy filters enabled.

**Comment by tholman** [comment]
For the record, change the "back-to-top" class, so hopefully that fixed it all. If not, perhaps its something with the inline svg that its blocking.

**Comment by Baldrs** [comment]
@tholman it is ok now, thank for your quick response.

**Comment by tholman** [comment]
Awesome! :dancer:
