### ISSUE TITLE
Don't ignore user scroll

### ISSUE THREAD

**Issue by mdix** [tholman/elevator.js#77]
If the user clicks the trigger to scroll up, but during the upscroll desides that he wants to scroll in another direction / stop the scroll, the user should be able to do so by scrolling. elevator.js should then stop the scrolling.

**Comment by tholman** [comment]
Appreciate the issue opening up, but there is no emergency stop on this elevator :o

**Comment by alanyee** [comment]
You can stop the elevator if your mouse (e.g. Logitech MX Master) has smart scrolling.
