### ISSUE TITLE
No "close door" button

### ISSUE THREAD

**Issue by dmackerman** [tholman/elevator.js#8]
I'd really like to use this library, but without a force close door button I'm afraid it has no place in our application.

**Comment by tjhill** [comment]
Agreed - When I'm scrolling from the bad guys as fast as I can... I don't want to wait for the doors to close themselves! ;)

**Comment by tholman** [comment]
Hahaha, indeed, this is one of those open face elevators... not so dissimilar to the ones in Titanic.

Bad for zombie scenarios as well.
