### ISSUE TITLE
Breaks on IE8 due to lack of Audio API support

### ISSUE THREAD

**Issue by joaocunha** [tholman/elevator.js#85]
Elevator breaks on IE8 and I'm blessed to work on a product that still supports it.

Will PR a fix today (basically checking for the lack of it and `return` afterwards).

**Comment by tholman** [comment]
I don't think ie8 supports the `<audio>` element either...?

**Comment by joaocunha** [comment]
@tholman most definitely, no. I hotfixed it with `if (!window.Audio) return;` over here.

**Comment by tholman** [comment]
Ahh, right, right!

Awesome. Definitely send a PR in when you have the time :D

**Comment by tholman** [comment]
Done.

**Comment by joaocunha** [comment]
Sorry, @tholman! Got into a hectic week and completely forgot this one.

I'll keep an eye on the issues to jump in another time.

**Comment by tholman** [comment]
No problem. The fix in https://github.com/tholman/elevator.js/commit/3a8108634d0314a228285d9c4636bd5015d08300 works for you, right?

**Comment by joaocunha** [comment]
@tholman not really. It should be one of the very first checks, actually, as `element.addEventListener` also isn't available on IE8.

https://github.com/tholman/elevator.js/blob/3a8108634d0314a228285d9c4636bd5015d08300/elevator.js#L186

A bit of extra care is needed on invocation, too:

```js
window.onload = function() {
  var elevator = new Elevator({
    mainAudio: '/src/to/audio.mp3',
    endAudio: '/src/to/end-audio.mp3'
  });
}

// elevate() is undefined in IE8, cause we return'ed earlier
elevator.elevate();
```

We just gotta make sure that IE8 (or any other browser that doesn't support the Audio API) can actually access `.elevate()` - otherwise developers would need to add the check (or a try/catch) on invocation, too, and I think that's not ideal.

Makes sense?

**Comment by tholman** [comment]
Urgh, ie8 is the pits :dancer:
