### ISSUE TITLE
Scrolling within a element?

### ISSUE THREAD

**Issue by shmshrbali** [tholman/elevator.js#92]
Hi loved the plugin, since i am a beginner in javascript, i was trying to attach the plugin to a element within the page that has overflow scroll. (long content div && body height 100%). I was wondering how do i about doing that?

**Comment by tholman** [comment]
Hey,

This isn't really in the scope of elevator.js, but if you were to do it, you'd need to change the `body` element in the script, and also line 66 (where the scrolling happens) - https://github.com/tholman/elevator.js/blob/master/elevator.js#L66

:)
