### ISSUE TITLE
The demo works poorly on android using Chrome

### ISSUE THREAD

**Issue by DoWhileGeek** [tholman/elevator.js#96]

**Comment by tholman** [comment]
Elaborate dude.

**Comment by DoWhileGeek** [comment]
Sure thing,

Elevator music starts 0.25 - 0.5 seconds after the scoll upwards begins.

Elevator music stops before it reaches the top, I assume to clear the air for the satisfying ding clip, but the ding clip never plays.

**Comment by DoWhileGeek** [comment]
I assume this is related to #93.

**Comment by tholman** [comment]
Sounds like a mix of that, and not preloading! :o

**Comment by tholman** [comment]
That said, the library is kind of meant as a joke, not really as something we should all be using in production. So I'm closing this off!
