### ISSUE TITLE
add tags for each version

### ISSUE THREAD

**Issue by maruilian11** [tholman/elevator.js#98]
would you please consider adding tags for each version so that we can add your lib on https://cdnjs.com with **git auto-update**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5529

**Comment by tholman** [comment]
Same with #97

**Comment by maruilian11** [comment]
feel very sorry!

**Comment by tholman** [comment]
Urgh, I know, I know. Its just that the project is made as a joke... I can't bare to bring myself to add code for all of the 50 different package managers out there (or even the popular ones) ... much rather move onto creating something new and fun!

**Comment by maruilian11** [comment]
ok, i see :+1:

**Comment by omkelderman** [comment]
why not accept pull requests for it ^^ maybe someone else (not me xd) can do it
